### ISSUE TITLE
Failed to process proto source files.: must specify at least one import path if any absolute file paths are given

### ISSUE THREAD

**Issue by shackra** [fullstorydev/grpcui#192]
Trying to run gRPCUI in a Docker compose installation like this:

```
  grpcui:
    image: fullstorydev/grpcui:latest
    networks:
      - app-tier
    restart: always
    depends_on:
      - rating-symbols
    ports:
      - 9006:8080
    volumes:
      - ./app/project/proto:/app/project/proto
    entrypoint: ["/bin/grpcui", "-bind=0.0.0.0", "-port=8080", "-plaintext", "-default-header='Authorization: Bearer ???'", "-proto=/app/project/proto/project.proto", "project-service:50051"]
```

however, checking the logs I get:

```
grpcui_1           | Failed to process proto source files.: must specify at least one import path if any absolute file paths are given
grpcui_1           | Failed to process proto source files.: must specify at least one import path if any absolute file paths are given
grpcui_1           | Failed to process proto source files.: must specify at least one import path if any absolute file paths are given
grpcui_1           | Failed to process proto source files.: must specify at least one import path if any absolute file paths are given
grpcui_1           | Failed to process proto source files.: must specify at least one import path if any absolute file paths are given
grpcui_1           | Failed to process proto source files.: must specify at least one import path if any absolute file paths are given
grpcui_1           | Failed to process proto source files.: must specify at least one import path if any absolute file paths are given
grpcui_1           | Failed to process proto source files.: must specify at least one import path if any absolute file paths are given
grpcui_1           | Failed to process proto source files.: must specify at least one import path if any absolute file paths are given
grpcui_1           | Failed to process proto source files.: must specify at least one import path if any absolute file paths are given
grpcui_1           | Failed to process proto source files.: must specify at least one import path if any absolute file paths are given
grpcui_1           | Failed to process proto source files.: must specify at least one import path if any absolute file paths are given
grpcui_1           | Failed to process proto source files.: must specify at least one import path if any absolute file paths are given
grpcui_1           | Failed to process proto source files.: must specify at least one import path if any absolute file paths are given
grpcui_1           | Failed to process proto source files.: must specify at least one import path if any absolute file paths are given
grpcui_1           | Failed to process proto source files.: must specify at least one import path if any absolute file paths are given
grpcui_1           | Failed to process proto source files.: must specify at least one import path if any absolute file paths are given
grpcui_1           | Failed to process proto source files.: must specify at least one import path if any absolute file paths are given
grpcui_1           | Failed to process proto source files.: must specify at least one import path if any absolute file paths are given
grpcui_1           | Failed to process proto source files.: must specify at least one import path if any absolute file paths are given
grpcui_1           | Failed to process proto source files.: must specify at least one import path if any absolute file paths are given
grpcui_1           | Failed to process proto source files.: must specify at least one import path if any absolute file paths are given
grpcui_1           | Failed to process proto source files.: must specify at least one import path if any absolute file paths are given
```

what and how am I supposed to import to have gRPCUI working with that compose configuration?
